package com.mycompany.finalems;

import javax.swing.*;
import java.awt.*;

public class EditEmployee extends javax.swing.JFrame {
    EmployeeInfo currentEmp;
    int empNum;
    private MyHashTable masterHashTable;
    public String EN; public int eN;
    public String fN;
    public String lN;
    public String g;
    public String wL;
    public String DR; public int dR;
    public String HDM; public int hDM;
    public String HDD; public int hDD;
    public String HDY; public int hDY;
    public int eT = -1;  
    public String YS; public int yS;
    public String HW; public int hW;
    public String HPW; public int hPW;
    public String WPY; public int wPY;
    
    public EditEmployee() {
        initComponents();
        fullTimeEmployeeLabel.setVisible(false);
        yearlySalaryLabel.setVisible(false);
        yearlySalaryTextField.setVisible(false);
        
        partTimeEmployeeLabel.setVisible(false);
        hourlyWageLabel.setVisible(false);
        hourlyWageTextField.setVisible(false);
        hoursPerWeekLabel.setVisible(false);
        hoursPerWeekTextField.setVisible(false);
        weeksPerYearLabel.setVisible(false);
        weeksPerYearTextField.setVisible(false);
        submitButton.setVisible(true);
        }
    
    public void displayOldInfo(int empNum){
        this.empNum = empNum;
        currentEmp = getReferenceValueFromEmpNum(empNum); 
        
        employeeNumberTextField.setText(String.valueOf(currentEmp.getEmpNum()));
        firstNameTextField.setText(currentEmp.getFirstName());
        lastNameTextField.setText(currentEmp.getLastName());
        genderComboBox.setSelectedItem(currentEmp.getGender());
        workLocationComboBox.setSelectedItem(currentEmp.getWorkLoc());
        deductionRateTextField.setText(String.valueOf((int)currentEmp.getDeductRate()));
        hireDateMonthComboBox.setSelectedItem(String.valueOf(currentEmp.getHireDateMonth()));
        hireDateDayComboBox.setSelectedItem(String.valueOf(currentEmp.getHireDateDay()));
        hireDateYearComboBox.setSelectedItem(String.valueOf(currentEmp.getHireDateYear()));

        
        if(currentEmp instanceof FTE){
            fullTimeRadioButton.setSelected(true);
            fullTimeEmployeeLabel.setVisible(true);
            yearlySalaryLabel.setVisible(true);
            yearlySalaryTextField.setVisible(true);
            FTE theFTE = (FTE) currentEmp;
            yearlySalaryTextField.setText(String.valueOf((int)theFTE.getGrossSalary()));
            eT = 1;
        }
        else if(currentEmp instanceof PTE){
           partTimeRadioButton.setSelected(true);
           partTimeEmployeeLabel.setVisible(true);
           hourlyWageLabel.setVisible(true);
           hourlyWageTextField.setVisible(true);
           hoursPerWeekLabel.setVisible(true);
           hoursPerWeekTextField.setVisible(true);
           weeksPerYearLabel.setVisible(true);
           weeksPerYearTextField.setVisible(true);
           submitButton.setVisible(true);
           PTE thePTE = (PTE) currentEmp;
           hourlyWageTextField.setText(String.valueOf((int)thePTE.getHourlyWage()));
           hoursPerWeekTextField.setText(String.valueOf((int)thePTE.getHoursPerWeek()));
           weeksPerYearTextField.setText(String.valueOf((int)thePTE.getWeeksPerYear()));
           eT = 0;
    }
    }
    
    public void setMasterHashTable(MyHashTable theRefValue){
        masterHashTable = theRefValue;
    }
    
    public EmployeeInfo getReferenceValueFromEmpNum(int num){
        for(int i = 0; i<masterHashTable.buckets.length; i++){
            for(int j = 0; j<masterHashTable.buckets[i].size(); j++){
                EmployeeInfo currentEmp = masterHashTable.buckets[i].get(j);
                int currentEmpNum = currentEmp.getEmpNum();
                if(currentEmpNum  == num){
                    return currentEmp;
                }
            }
        }
        return null;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        addEmployeeLabel = new javax.swing.JLabel();
        employeeNumberLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        workLocationLabel = new javax.swing.JLabel();
        deductionRateLabel = new javax.swing.JLabel();
        hireDateLabel = new javax.swing.JLabel();
        typeOfEmployeeLabel = new javax.swing.JLabel();
        employeeNumberTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        workLocationComboBox = new javax.swing.JComboBox<>();
        deductionRateTextField = new javax.swing.JTextField();
        hireDateMonthComboBox = new javax.swing.JComboBox<>();
        hireDateDayComboBox = new javax.swing.JComboBox<>();
        hireDateYearComboBox = new javax.swing.JComboBox<>();
        fullTimeRadioButton = new javax.swing.JRadioButton();
        partTimeRadioButton = new javax.swing.JRadioButton();
        cancelButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        fullTimeEmployeeLabel = new javax.swing.JLabel();
        yearlySalaryLabel = new javax.swing.JLabel();
        yearlySalaryTextField = new javax.swing.JTextField();
        hoursPerWeekLabel = new javax.swing.JLabel();
        weeksPerYearLabel = new javax.swing.JLabel();
        hoursPerWeekTextField = new javax.swing.JTextField();
        weeksPerYearTextField = new javax.swing.JTextField();
        hourlyWageLabel = new javax.swing.JLabel();
        hourlyWageTextField = new javax.swing.JTextField();
        partTimeEmployeeLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("%");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        addEmployeeLabel.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        addEmployeeLabel.setText("Edit Employee");

        employeeNumberLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        employeeNumberLabel.setText("Employee Number:");

        firstNameLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        firstNameLabel.setText("First Name:");

        lastNameLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lastNameLabel.setText("Last Name:");

        genderLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        genderLabel.setText("Gender:");

        workLocationLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        workLocationLabel.setText("Work Location:");

        deductionRateLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        deductionRateLabel.setText("Deduction Rate:");

        hireDateLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        hireDateLabel.setText("Hire Date:");

        typeOfEmployeeLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        typeOfEmployeeLabel.setText("Type of Employee:");

        employeeNumberTextField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        employeeNumberTextField.setMinimumSize(new java.awt.Dimension(150, 18));
        employeeNumberTextField.setPreferredSize(new java.awt.Dimension(150, 18));

        firstNameTextField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        firstNameTextField.setMinimumSize(new java.awt.Dimension(150, 18));
        firstNameTextField.setPreferredSize(new java.awt.Dimension(150, 18));

        lastNameTextField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        lastNameTextField.setMinimumSize(new java.awt.Dimension(150, 18));
        lastNameTextField.setPreferredSize(new java.awt.Dimension(150, 18));

        genderComboBox.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT A GENDER", "Female", "Male", "Other" }));
        genderComboBox.setMinimumSize(new java.awt.Dimension(150, 20));
        genderComboBox.setPreferredSize(new java.awt.Dimension(150, 20));

        workLocationComboBox.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        workLocationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT A LOCATION", "Mississauga", "Toronto", "Oakville" }));
        workLocationComboBox.setMinimumSize(new java.awt.Dimension(150, 20));
        workLocationComboBox.setPreferredSize(new java.awt.Dimension(150, 20));

        deductionRateTextField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        deductionRateTextField.setPreferredSize(new java.awt.Dimension(64, 18));

        hireDateMonthComboBox.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        hireDateMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        hireDateMonthComboBox.setPreferredSize(new java.awt.Dimension(72, 18));

        hireDateDayComboBox.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        hireDateDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        hireDateDayComboBox.setPreferredSize(new java.awt.Dimension(72, 18));

        hireDateYearComboBox.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        hireDateYearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Y", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        hireDateYearComboBox.setPreferredSize(new java.awt.Dimension(72, 18));

        buttonGroup1.add(fullTimeRadioButton);
        fullTimeRadioButton.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        fullTimeRadioButton.setText("Full Time");
        fullTimeRadioButton.setPreferredSize(new java.awt.Dimension(76, 18));
        fullTimeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(partTimeRadioButton);
        partTimeRadioButton.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        partTimeRadioButton.setText("Part Time");
        partTimeRadioButton.setPreferredSize(new java.awt.Dimension(76, 18));
        partTimeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeRadioButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        fullTimeEmployeeLabel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        fullTimeEmployeeLabel.setText("Full Time Employee");

        yearlySalaryLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        yearlySalaryLabel.setText("Yearly Salary:");

        yearlySalaryTextField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        yearlySalaryTextField.setMinimumSize(new java.awt.Dimension(150, 18));
        yearlySalaryTextField.setPreferredSize(new java.awt.Dimension(150, 18));

        hoursPerWeekLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        hoursPerWeekLabel.setText("Hours/Week:");

        weeksPerYearLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        weeksPerYearLabel.setText("Weeks/Year:");

        hoursPerWeekTextField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        hoursPerWeekTextField.setMinimumSize(new java.awt.Dimension(150, 18));
        hoursPerWeekTextField.setPreferredSize(new java.awt.Dimension(150, 18));

        weeksPerYearTextField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        weeksPerYearTextField.setMinimumSize(new java.awt.Dimension(150, 18));
        weeksPerYearTextField.setPreferredSize(new java.awt.Dimension(150, 18));

        hourlyWageLabel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        hourlyWageLabel.setText("Hourly Wage:");

        hourlyWageTextField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        hourlyWageTextField.setPreferredSize(new java.awt.Dimension(150, 18));

        partTimeEmployeeLabel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        partTimeEmployeeLabel.setText("Part Time Employee");

        deleteButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        deleteButton.setText("Delete Employee");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(employeeNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNameLabel)
                            .addComponent(workLocationLabel)
                            .addComponent(genderLabel)
                            .addComponent(deductionRateLabel)
                            .addComponent(hireDateLabel)
                            .addComponent(typeOfEmployeeLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hireDateMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hireDateDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hireDateYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fullTimeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(partTimeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(workLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(deductionRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hourlyWageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hourlyWageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(submitButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hoursPerWeekLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hoursPerWeekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(weeksPerYearLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weeksPerYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(partTimeEmployeeLabel)
                            .addComponent(fullTimeEmployeeLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(79, 79, 79)
                        .addComponent(yearlySalaryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearlySalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton))
                            .addComponent(addEmployeeLabel))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(addEmployeeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeNumberLabel)
                    .addComponent(employeeNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullTimeEmployeeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel)
                    .addComponent(yearlySalaryLabel)
                    .addComponent(yearlySalaryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameLabel)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(workLocationLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deductionRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deductionRateLabel)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hireDateMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hireDateLabel)
                            .addComponent(hireDateDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hireDateYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fullTimeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(partTimeRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeOfEmployeeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton)
                            .addComponent(submitButton)
                            .addComponent(deleteButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(partTimeEmployeeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hourlyWageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hourlyWageLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hoursPerWeekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hoursPerWeekLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weeksPerYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(weeksPerYearLabel))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    
        public boolean doesEmployeeExist(int num){
           for(int i = 0; i<masterHashTable.buckets.length; i++){
               for(int j = 0; j<masterHashTable.buckets[i].size(); j++){
                   int currentEmpNum = masterHashTable.buckets[i].get(j).getEmpNum();
                   if(currentEmpNum == num){
                       if(currentEmpNum == empNum){
                           return false;
                       }
                       else{
                           return true;
                       }
                   }
               }
           }
           return false;
    }
        
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        EN = employeeNumberTextField.getText().strip();
        fN = firstNameTextField.getText().strip();
        lN = lastNameTextField.getText().strip();
        g = (String) genderComboBox.getSelectedItem();
        wL = (String) workLocationComboBox.getSelectedItem();
        DR = deductionRateTextField.getText().strip();
        HDM = (String) hireDateMonthComboBox.getSelectedItem();
        HDD = (String) hireDateDayComboBox.getSelectedItem();
        HDY = (String) hireDateYearComboBox.getSelectedItem();
        if(eT == 1){
            YS = yearlySalaryTextField.getText().strip();
        }   
        else if(eT == 0){
            HW = hourlyWageTextField.getText().strip();
            HPW = hoursPerWeekTextField.getText().strip();
            WPY = weeksPerYearTextField.getText().strip();
        }
    
    //Error Checking 
                boolean flag1 = false; //employee number 
                boolean flag2 = false; //deduction rate 
                boolean flag3 = false; //hourly wage
                boolean flag4 = false; //hours per week
                boolean flag5 = false; //everything is good flag 
                
                boolean flag6 = false;
           //Employee Number
                try{
                    eN = Integer.parseInt(EN);
                    flag1 = true;
                 }
                 catch(NumberFormatException e){
                     errorCall(1);
                     return;
                 }
                if(flag1 == true){
                    if(eN < 0){
                        errorCall(2);
                    }
                    else if(doesEmployeeExist(eN) == true){
                            errorCall(21);
                    }
           //First Name
                    else if(fN.equals("")){
                        errorCall(3);
                    }
          //Last Name
                    else if(lN.equals("")){
                        errorCall(4);
                     }
           //Gender
                    else if(g.equals("SELECT A GENDER")){
                        errorCall(5);
                    }
           //Location
                    else if(wL.equals("SELECT A LOCATION")){
                        errorCall(6);
                    }
           //Deduction Rate
                    else{
                        try{
                            dR = Integer.parseInt(DR);
                            flag2 = true;
                        }
                        catch(NumberFormatException e){
                            errorCall(7);
                            return;
                        }
                    }
                    if(flag2 == true){
                        if(dR < 0){
                            errorCall(8);
                        }
                        else if(dR > 100){
                            errorCall(9);
                        }
            //Hire Month
                        else if(HDM.equals("M")){
                            errorCall(10);
                        }
                        else{
                            hDM = Integer.parseInt(HDM);
           //Hire Date
                            if(HDD.equals("D")){
                                errorCall(11);
                            }
                            else{
                                hDD = Integer.parseInt(HDD);
          //Hire Year
                                if(HDY.equals("Y")){
                                    errorCall(12);
                                }
                                else{
                                    hDY = Integer.parseInt(HDY);
                                    flag6 = true;
                                }
                            }
                        }
                     if(flag6 == true){
          //Yearly Salary
                            if(eT == 1){
                                try{
                                    yS = Integer.parseInt(YS);
                                }
                                catch(NumberFormatException e){
                                    errorCall(13);
                                    return;
                                }
                                if(yS < 0){
                                    errorCall(14);
                                }
                                else{
                                         FTE theFTE = new FTE(eN, fN, lN, g, wL, dR, hDM, hDD, hDY, yS);
                                         masterHashTable.removeEmployee(currentEmp.getEmpNum());
                                         masterHashTable.addEmployee(theFTE);
                                         errorCall(23);
                                         this.dispose();
                                }
                            }
                            else{
          //Hourly Wage
                                try{
                                    hW = Integer.parseInt(HW);
                                    if(hW < 0){
                                        errorCall(15);
                                        return;
                                    }
                                    flag3 = true;
                                }
                                catch(NumberFormatException e){
                                    errorCall(16);
                                    return;
                                }
          //Hours Per Week
                                if(flag3 == true){
                                    try{
                                         hPW = Integer.parseInt(HPW);
                                          if(hPW < 0){
                                            errorCall(17);
                                             return;
                                         }
                                         flag4 = true;
                                        }
                                        catch(NumberFormatException e){
                                            errorCall(18);
                                            return;
                                        }
                                    if(flag4 == true){
          //Weeks Per Year
                                        try{
                                            wPY = Integer.parseInt(WPY);
                                            if(wPY < 0){
                                                errorCall(19);
                                                return;
                                            }
                                            else{
                                                    PTE thePTE = new PTE(eN, fN,lN, g, wL, dR, hDM, hDD, hDY, hW, hPW, wPY);
                                                    masterHashTable.removeEmployee(currentEmp.getEmpNum());
                                                    masterHashTable.addEmployee(thePTE);
                                                    errorCall(23);
                                                    this.dispose();
                                            }
                                        }
                                        catch(NumberFormatException e){
                                             errorCall(20);
                                             return;
                                        }
                                    }
                                }
                            }
                     }
                        }
                    }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        ConfirmationScreen comScreen = new ConfirmationScreen(currentEmp, masterHashTable);
        comScreen.setVisible(true);
        comScreen.messageUpdate("Are you use you would like to delete" + currentEmp.getEmpNum() + "?");
        this.dispose();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void fullTimeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeRadioButtonActionPerformed
             eT = 1;
            fullTimeEmployeeLabel.setVisible(true);
            yearlySalaryLabel.setVisible(true);
            yearlySalaryTextField.setVisible(true);
        
            partTimeEmployeeLabel.setVisible(false);
            hourlyWageLabel.setVisible(false);
            hourlyWageTextField.setVisible(false);
            hoursPerWeekLabel.setVisible(false);
            hoursPerWeekTextField.setVisible(false);
            weeksPerYearLabel.setVisible(false);
            weeksPerYearTextField.setVisible(false);
            submitButton.setVisible(true);
    }//GEN-LAST:event_fullTimeRadioButtonActionPerformed

    private void partTimeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeRadioButtonActionPerformed
                    eT = 0;        
            fullTimeEmployeeLabel.setVisible(false);
            yearlySalaryLabel.setVisible(false);
            yearlySalaryTextField.setVisible(false);

            partTimeEmployeeLabel.setVisible(true);
            hourlyWageLabel.setVisible(true);
            hourlyWageTextField.setVisible(true);
            hoursPerWeekLabel.setVisible(true);
            hoursPerWeekTextField.setVisible(true);
            weeksPerYearLabel.setVisible(true);
            weeksPerYearTextField.setVisible(true);
            submitButton.setVisible(true);
    }//GEN-LAST:event_partTimeRadioButtonActionPerformed

    //If the entered information passes all the error checking above, create a new employee with the given information and add to the hashtable
    public void errorCall(int num){
         
            ErrorScreen errorScreen = new ErrorScreen();
           errorScreen.setVisible(true);
           errorScreen.displayError(num);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addEmployeeLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel deductionRateLabel;
    private javax.swing.JTextField deductionRateTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel employeeNumberLabel;
    private javax.swing.JTextField employeeNumberTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel fullTimeEmployeeLabel;
    private javax.swing.JRadioButton fullTimeRadioButton;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JComboBox<String> hireDateDayComboBox;
    private javax.swing.JLabel hireDateLabel;
    private javax.swing.JComboBox<String> hireDateMonthComboBox;
    private javax.swing.JComboBox<String> hireDateYearComboBox;
    private javax.swing.JLabel hourlyWageLabel;
    private javax.swing.JTextField hourlyWageTextField;
    private javax.swing.JLabel hoursPerWeekLabel;
    private javax.swing.JTextField hoursPerWeekTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel partTimeEmployeeLabel;
    private javax.swing.JRadioButton partTimeRadioButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel typeOfEmployeeLabel;
    private javax.swing.JLabel weeksPerYearLabel;
    private javax.swing.JTextField weeksPerYearTextField;
    private javax.swing.JComboBox<String> workLocationComboBox;
    private javax.swing.JLabel workLocationLabel;
    private javax.swing.JLabel yearlySalaryLabel;
    private javax.swing.JTextField yearlySalaryTextField;
    // End of variables declaration//GEN-END:variables

}
