package com.mycompany.finalems;

public class ErrorScreen extends javax.swing.JFrame {

    public ErrorScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorMessageLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        errorMessageLabel.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        errorMessageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorMessageLabel.setText("Error Message");

        closeButton.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(20, 20, 20))
            .addComponent(errorMessageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(closeButton)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ErrorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ErrorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ErrorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ErrorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ErrorScreen().setVisible(true);
            }
        });
    }
    
    public void displayError(int num){
        if(num == 1){
            errorMessageLabel.setText("The employee number has to be a number");
        }
        else if(num == 2){
            errorMessageLabel.setText("The employee number has to be positive");
        }
        else if(num == 3){
            errorMessageLabel.setText("Please enter a first name");
        }
        else if(num == 4){
            errorMessageLabel.setText("Please enter a last name");
        }
        else if(num == 5){
            errorMessageLabel.setText("Please select a gender");
        }
        else if(num == 6){
            errorMessageLabel.setText("Please select a work location");
        }
        else if(num == 7){
            errorMessageLabel.setText("The deduction rate has to be a number"); 
        }
        else if(num == 8){
            errorMessageLabel.setText("The deduction rate cannot be less than 0");
        }
        else if(num == 9 ){
            errorMessageLabel.setText("The deduction rate cannot be more than 100");
        }
        else if(num == 10){
            errorMessageLabel.setText("Please select a hire month");
        }
        else if(num == 11){
            errorMessageLabel.setText("Please select a hire day");
        }
        else if(num == 12){
            errorMessageLabel.setText("Please select a hire year");
        }
        else if(num == 13){
            errorMessageLabel.setText("The yearly salary must be a number");
        }
        else if(num ==14){
            errorMessageLabel.setText("The yearly salary must be a positive number");
        }
        else if(num == 15){
            errorMessageLabel.setText("The hourly wage must be a positive number");
        }
        else if(num == 16){
            errorMessageLabel.setText("The hourly wage must be a number");
        }
        else if(num == 17){
            errorMessageLabel.setText("The hours per week must be a positive number"); 
        }
        else if(num == 18){
            errorMessageLabel.setText("The hours per week must be a number");
        }
        else if(num == 19){
            errorMessageLabel.setText("The weeks per year must be a positive number");
        }
        else if(num == 20){
            errorMessageLabel.setText("The weeks per year must be a number");
        }
        else if(num == 21){
            errorMessageLabel.setText("The employee number your entered is already in use");
        }
        else if(num == 22){
            errorMessageLabel.setText("Employee has been removed");
        }
        else if(num ==23){
            errorMessageLabel.setText("The employee was updated");
        }
        else if(num ==24){
            errorMessageLabel.setText("All employees have been removed");
        }
        else if(num ==25){
            errorMessageLabel.setText("Error saving employees to file, please try again");
        }
        else if(num ==26){
            errorMessageLabel.setText("Error loading employees from file, please try again");
        }
        else if(num ==27){
            errorMessageLabel.setText("Employees sucessfully saved to UserData.txt");
        }
        else if(num ==28){
            errorMessageLabel.setText("Employees succesfully uploaded from UserData.txt");
        }
        else if(num == 29){
            errorMessageLabel.setText("Please enter data into a search field and try again");
        }
        else if(num ==30){
            errorMessageLabel.setText("Employee added succesfully");
        }
    }
            //errorMessageLabel.setText("");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel errorMessageLabel;
    // End of variables declaration//GEN-END:variables
}
